apiVersion: v1
kind: Service
metadata:
  name: flux-api
  namespace: flux-system
  labels:
    app: flux-api-crud
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: flux-api-crud
