apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-db-pvc.yaml
  - api-crud-deployment.yaml
  - api-readonly-deployment.yaml
  - api-service.yaml
  - api-readonly-service.yaml
