/*
 * Flux ResourceSet Internal API
 *
 * Internal API for Flux phone-home read-only and CRUD operations
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterPlatformComponentsInner {
    #[serde(rename = "component_path", skip_serializing_if = "Option::is_none")]
    pub component_path: Option<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "oci_tag", skip_serializing_if = "Option::is_none")]
    pub oci_tag: Option<String>,
}

impl ClusterPlatformComponentsInner {
    pub fn new(enabled: bool, id: String) -> ClusterPlatformComponentsInner {
        ClusterPlatformComponentsInner {
            component_path: None,
            enabled,
            id,
            oci_tag: None,
        }
    }
}
