/*
 * Flux ResourceSet Internal API
 *
 * Internal API for Flux phone-home read-only and CRUD operations
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterNamespacesInner {
    #[serde(rename = "id")]
    pub id: String,
}

impl ClusterNamespacesInner {
    pub fn new(id: String) -> ClusterNamespacesInner {
        ClusterNamespacesInner { id }
    }
}
