/*
 * Flux ResourceSet Internal API
 *
 * Internal API for Flux phone-home read-only and CRUD operations
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformComponent {
    /// Whether the template appends /{environment} to component_path.
    #[serde(
        rename = "cluster_env_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub cluster_env_enabled: Option<bool>,
    /// Base path within the OCI artifact.
    #[serde(rename = "component_path")]
    pub component_path: String,
    /// Upstream app version.
    #[serde(rename = "component_version")]
    pub component_version: String,
    /// Component dependencies.
    #[serde(rename = "depends_on")]
    pub depends_on: Vec<String>,
    /// The unique component identifier.
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    /// Default OCI artifact tag.
    #[serde(rename = "oci_tag")]
    pub oci_tag: String,
    /// OCI registry URL for component source.
    #[serde(rename = "oci_url")]
    pub oci_url: String,
}

impl CreatePlatformComponent {
    pub fn new(
        component_path: String,
        component_version: String,
        depends_on: Vec<String>,
        id: Option<serde_json::Value>,
        oci_tag: String,
        oci_url: String,
    ) -> CreatePlatformComponent {
        CreatePlatformComponent {
            cluster_env_enabled: None,
            component_path,
            component_version,
            depends_on,
            id,
            oci_tag,
            oci_url,
        }
    }
}
