/*
 * Flux ResourceSet Internal API
 *
 * Internal API for Flux phone-home read-only and CRUD operations
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRolebinding {
    /// Rolebinding identifier.
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    /// Role name to bind.
    #[serde(rename = "role")]
    pub role: String,
    /// Subject references for the binding.
    #[serde(rename = "subjects")]
    pub subjects: Vec<std::collections::HashMap<String, serde_json::Value>>,
}

impl CreateRolebinding {
    pub fn new(
        id: Option<serde_json::Value>,
        role: String,
        subjects: Vec<std::collections::HashMap<String, serde_json::Value>>,
    ) -> CreateRolebinding {
        CreateRolebinding { id, role, subjects }
    }
}
