/*
 * Flux ResourceSet Internal API
 *
 * Internal API for Flux phone-home read-only and CRUD operations
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCluster {
    /// Fully qualified DNS name for phone-home lookups.
    #[serde(rename = "cluster_dns", skip_serializing_if = "Option::is_none")]
    pub cluster_dns: Option<String>,
    /// Display name for the cluster.
    #[serde(rename = "cluster_name", skip_serializing_if = "Option::is_none")]
    pub cluster_name: Option<String>,
    /// Deployment tier for the cluster.
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<Environment>,
    /// The stable unique cluster identifier.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<serde_json::Value>>,
    /// Kubernetes distribution version.
    #[serde(rename = "k0s_version", skip_serializing_if = "Option::is_none")]
    pub k0s_version: Option<String>,
    /// Namespace references managed for this cluster.
    #[serde(rename = "namespaces", skip_serializing_if = "Option::is_none")]
    pub namespaces: Option<Vec<models::ClusterNamespacesInner>>,
    /// Desired node count for the cluster.
    #[serde(rename = "node_count", skip_serializing_if = "Option::is_none")]
    pub node_count: Option<i32>,
    /// Per-cluster per-component key-value substitutions.
    #[serde(rename = "patches", skip_serializing_if = "Option::is_none")]
    pub patches:
        Option<std::collections::HashMap<String, std::collections::HashMap<String, String>>>,
    /// Component references assigned to this cluster.
    #[serde(
        rename = "platform_components",
        skip_serializing_if = "Option::is_none"
    )]
    pub platform_components: Option<Vec<models::ClusterPlatformComponentsInner>>,
    /// Rolebinding references managed for this cluster.
    #[serde(rename = "rolebindings", skip_serializing_if = "Option::is_none")]
    pub rolebindings: Option<Vec<models::ClusterNamespacesInner>>,
    /// VM image used to provision nodes.
    #[serde(rename = "vm_image", skip_serializing_if = "Option::is_none")]
    pub vm_image: Option<String>,
}

impl UpdateCluster {
    pub fn new() -> UpdateCluster {
        UpdateCluster {
            cluster_dns: None,
            cluster_name: None,
            environment: None,
            id: None,
            k0s_version: None,
            namespaces: None,
            node_count: None,
            patches: None,
            platform_components: None,
            rolebindings: None,
            vm_image: None,
        }
    }
}
/// Deployment tier for the cluster.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Environment {
    #[serde(rename = "dev")]
    Dev,
    #[serde(rename = "qa")]
    Qa,
    #[serde(rename = "uat")]
    Uat,
    #[serde(rename = "prod")]
    Prod,
}

impl Default for Environment {
    fn default() -> Environment {
        Self::Dev
    }
}
