/*
 * Flux ResourceSet Internal API
 *
 * Internal API for Flux phone-home read-only and CRUD operations
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePlatformComponent {
    /// Whether the template appends /{environment} to component_path.
    #[serde(
        rename = "cluster_env_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub cluster_env_enabled: Option<bool>,
    /// Base path within the OCI artifact.
    #[serde(rename = "component_path", skip_serializing_if = "Option::is_none")]
    pub component_path: Option<String>,
    /// Upstream app version.
    #[serde(rename = "component_version", skip_serializing_if = "Option::is_none")]
    pub component_version: Option<String>,
    /// Component dependencies.
    #[serde(rename = "depends_on", skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    /// The unique component identifier.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<serde_json::Value>>,
    /// Default OCI artifact tag.
    #[serde(rename = "oci_tag", skip_serializing_if = "Option::is_none")]
    pub oci_tag: Option<String>,
    /// OCI registry URL for component source.
    #[serde(rename = "oci_url", skip_serializing_if = "Option::is_none")]
    pub oci_url: Option<String>,
}

impl UpdatePlatformComponent {
    pub fn new() -> UpdatePlatformComponent {
        UpdatePlatformComponent {
            cluster_env_enabled: None,
            component_path: None,
            component_version: None,
            depends_on: None,
            id: None,
            oci_tag: None,
            oci_url: None,
        }
    }
}
